
package com.example.raza.networkrequestmanagment.network.constants;

public enum HttpResponseCode
{
    // 1xx informational
    CONTINUE ,
    SWITCHING_PROTOCOLS ,
    PROCESSING ,


    // 2xx success
    OK ,
    CREATED ,
    ACCEPTED ,
    NON_AUTHORITATIVE_INFO ,
    NO_CONTENT ,
    RESET_CONETNT ,
    PARTIAL_CONTENT ,
    MULTI_STATUS ,
    ALREADY_REPORTED ,
    IM_USED ,

    // 3xx redirection
    MULTIPLE_CHOICES ,
    MOVED_PERMANENTLY ,
    FOUND ,
    SEE_OTHER,
    NOT_MODIFIED,
    USE_PROXY ,
    SWITCH_PROXY ,
    TEMPORARY_REDIRECTED ,
    PERMANENT_REDIRECT ,

    // 4xx client error
    BAD_REQUEST ,
    UNAUTHORIZED ,
    PAYMENT_REQUIRED ,
    FORBIDDEN ,
    NOT_FOUND ,
    METHOD_NOT_ALLOWED ,
    NOT_ACCEPTIBLE ,
    PROXY_AUTH_REQUIRED ,
    REQUEST_TIMEOUT ,
    CONFLICT ,
    GONE ,
    LENGTH_REQUIRED ,
    PRECONDITION_FAILED ,
    PAYLOAD_TOO_LARGE ,
    URI_TOO_LONG ,
    UNSUPPORTED_MEDIA_TYPE ,
    RANGE_NOT_STAISFIABLE ,
    EXPECTATION_FAILED ,
    IM_TEAPOT ,
    MISDIRECTED_REQUEST ,
    UNPROCESSABLE_ENTITY ,
    LOCKED ,
    FAILED_DEPENDENCY ,
    UPGRADE_REQUIRED ,
    PRECONDITION_REQUIRED ,
    TOO_MANY_ERQUESTS ,
    REQUEST_HEADER_FIELDS_TOO_LARGE ,
    UNAVAILABLE_FOR_LEGAL_REASONS ,


    // 5xx server error
    INTERNAL_SERVER_ERROR ,
    NOT_IMPLEMENTED ,
    BAD_GATEWAY ,
    SERVICE_UNAVAILABLE ,
    GATEWAY_TIMEOUT ,
    HTTP_VERSION_NOT_SUPPORTED ,
    VARIANT_ALSO_NEGOTIATES ,
    INSUFFICIENT_STORAGE ,
    LOOP_DETECTED ,
    NOT_EXTENDED ,
    NETWORK_AUTH_REQUIRED,

    UNKNOWN
};